[versions]
agp = "9.0.1"

android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"

coil = "3.3.0"
compose-multiplatform = "1.10.1"
datastore = "1.2.0"
koin-bom = "4.1.1"
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.10.0"
ksp = "2.3.2"
ktor = "3.4.0"
lifecycle-viewmodel-compose = "2.9.6"
material-icons-extended = "1.7.3"
navigation3 = "1.0.0-alpha06"
room = "2.8.4"
sqlite = "2.6.2"
ui-tooling = "1.10.3"

[libraries]

# Jetbrains
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# Compose
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }

# Koin
koin-core = { module = "io.insert-koin:koin-core"}
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android"}
koin-compose = { module = "io.insert-koin:koin-compose"}

# Datastore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

#Preview
compose-ui-preview-android = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

coil-common = [
    "coil-compose",
    "coil-network-ktor"
]

compose-common = [
    "compose-components-resources",
    "compose-ui",
    "compose-preview",
    "compose-material",
    "compose-runtime",
    "compose-foundation",
    "navigation3-ui"
]

datastore-common = [
    "datastore-preferences",
    "datastore"
]

koin-common = [
    "koin-core",
    "koin-compose"
]

koin-android = [
    "koin-android"
]

kotlinx-common = [
    "kotlinx-coroutines-core",
    "kotlinx-serialization-json"
]

ktor-common = [
    "ktor-client-core",
    "ktor-negotiation",
    "ktor-json",
    "ktor-client-auth"
]
ktor-android = [
    "ktor-client-android",
    "ktor-client-okhttp"
]
ktor-desktop = [
    "ktor-client-java",
    "kotlinx-coroutines-swing",
    "ktor-client-okhttp"
]
ktor-wasmjs = [
    "ktor-client-js"
]
ktor-ios = [
    "ktor-client-darwin"
]
